# Generated by Django 2.2.12 on 2020-08-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='profile_img',
            field=models.ImageField(default='profile_img/avatar.png', upload_to='profile_img'),
        ),
    ]
