"""
Django settings for Eva project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'on95p24k0vs*6$(gnsrxf!-f+o_$wj)n@2%c8i2v!)wba2n^-j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # additional APPS
    'livereload',
    'account.apps.AccountConfig',
    'chef.apps.ChefConfig',
    'home.apps.HomeConfig',
    'menu.apps.MenuConfig',
    'staff.apps.StaffConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # additional middleware
    'livereload.middleware.LiveReloadScript',
]

ROOT_URLCONF = 'Eva.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # joining the templates DIR
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Eva.wsgi.application'


# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# sqlite3 database settings by default
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# postgres database settings
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': '******', # replace this with your database name e.g: (eva)
        'HOST': '******', # replace this with your database host e.g: (127.0.0.1)
        'USER': '******', # replace this with your database user e.g: (Jonh)
        'PASSWORD': '******', # replace this with your database password e.g: (123Jonh)
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# handling static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')

# handling media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# email handlering and settings

# # for testing below, uncomment this section
# # run this in the terminal to no the testing smtp.>>> $ python3 -m smtpd -n -c DebuggingServer 127.0.0.1:1025
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_HOST = '127.0.0.1'
# EMAIL_POST = '1025'
# EMAIL_HOST_USER = ''
# EMAIL_HOST_PASSWORD = ''
# EMAIL_USE_TLS = False
# EMAIL_USE_SSL = False



# # for real world below, uncomment this section if commented
# NOTICE:
# # 1>>> Please use an enviromental virable for securing your email and password
# # 2>>> Have to make changes in the gmail. Go to this URL after logging into your gmail.
# # https://myaccount.google.com/lesssecureapps
# # toggle NO if OFF
# # 3>>> and visit this also
# # https://accounts.google.com/DisplayUnlockCaptcha
# # click continue
# # ADDITION SECURETY 
# # Enable "Two way authentication on your gmail. And then visit this URL"
# # https://myaccount.google.com/apppasswords
# # create an app password to use for your app instead of your real gmail password
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = '******' # replace this with your gmail account EMAIL e.g: (123@gmail.com)
EMAIL_HOST_PASSWORD = '*******' # replace this with your gmail account PASSWORD e.g: (123abc)
EMAIL_PORT = 587

# NOTICE
# This credentials are only for gmail, other smtp companies have their own. So if using different smtp server.
# please google on how the set their's for django.