# Generated by Django 2.2.12 on 2020-08-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0002_auto_20200820_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='chef_img',
            field=models.ImageField(upload_to='chef_img'),
        ),
    ]
