# Generated by Django 2.2.12 on 2020-08-20 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0003_auto_20200820_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='joined_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
