# Generated by Django 2.2.12 on 2020-08-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
