# Generated by Django 2.2.12 on 2020-08-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200820_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='plate_info',
            field=models.TextField(default=True, max_length=2000, null=True),
        ),
    ]
