# Generated by Django 2.2.12 on 2020-08-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20200821_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dish_type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='plate_img',
            field=models.ImageField(default=None, upload_to='plate_img'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='plate_info',
            field=models.TextField(default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='recipies',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
