# Generated by Django 2.2.12 on 2020-08-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20200821_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_plate', models.IntegerField()),
                ('delivery_location', models.TextField(default=None, max_length=2000, null=True)),
            ],
        ),
    ]
