# Generated by Django 2.2.12 on 2020-08-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_deliverylocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylocation',
            name='ordering_plate',
            field=models.TextField(default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='deliverylocation',
            name='phone_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
