# Generated by Django 2.2.12 on 2020-08-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20200822_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(default=None, max_length=100, null=True)),
                ('number_of_person', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
